username: "vvoronova"
passwordFile: "C:\\dev\\pass.txt"
observeDirectory: "C://Users/valen/eclipse-workspace/aku/source-sync/"
activity: "http://uni-bamberg.de/mobi/kbms/simutool/Activity/Simulation"
contributor: "http://uni-bamberg.de/mobi/kbms/simutool/User/18779w"
dc_description: "Please enter a description"
dc_subject: "ssss"
dc_references: "rrrr"
attachment: "aaaa"
kgURL: "http://141.13.162.157:9000/simutool_kms/kg/api/document"
